name: iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # 1. Pobierz kod z repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ustaw Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      # 3. Uruchom testy
      - name: Run tests
          run: |
            xcodebuild test \
              -project Stronger.xcodeproj \
              -scheme Stronger \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'

